# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180807_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
